# Generated by Django 5.0 on 2023-12-29 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Famille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Panier",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=255)),
                ("code", models.CharField(default=0, max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PointDeVent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("wilaya", models.CharField(max_length=50)),
                ("moughataa", models.CharField(max_length=50)),
                ("gps_lat", models.IntegerField(default=0)),
                ("gps_long", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Prix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default=0, max_length=50)),
                ("valeur", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="PanierProduit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ponderation", models.FloatField()),
                (
                    "panier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_22240.panier",
                    ),
                ),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_22240.prix"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=255)),
                ("price_unit", models.FloatField(default=0)),
                ("code", models.CharField(default=0, max_length=255)),
                (
                    "famille_produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_22240.famille",
                    ),
                ),
            ],
        ),
    ]
