# Generated by Django 5.0 on 2024-01-08 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_22240", "0002_article"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
    ]
