# Generated by Django 5.0 on 2024-01-09 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_22240", "0002_initial"),
    ]

    operations = []
