# Generated by Django 5.0 on 2024-01-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_22240", "0003_auto_20240110_0020"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="moyenne_ponderee",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
